services:
  postgres:
    image: postgres:latest
    container_name: golang_postgres_crud
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1111
      POSTGRES_DB: urls_db
      PGDATA: ./var/lib/postgresql/data/pgdata
    ports:
      - "5422:5411"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    
volumes:
  pgdata:
    driver: local